name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'




      - name: Install frontend deps
        run: npm ci

      - name: Build frontend
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:3001



      - name: Install backend deps
        working-directory: api
        run: npm ci

      - name: Generate Prisma client
        working-directory: api
        run: npx prisma generate

      - name: Run unit tests (backend)
        working-directory: api
        run: npm test -- --ci

      - name: Build backend
        working-directory: api
        run: npm run build
